- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: install requirements
    shell: |
      . /var/lib/awx/venv/ansible/bin/activate
      umask 0022
      pip install ansible[azure] --ignore-installed
      deactivate
  - name: create security group that allows ssh 
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ network_security_group }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
